import type { CharacterClass } from "./combat";

export const CLASS_CATALOG: Record<string, CharacterClass> = {
  soldier: {
    id: 0x01,
    name: "Soldier",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["lawful", "neutral", "chaotic"],
    weatherResistance: 2,
    weightPenalty: 40,
    movementTypes: ["fast"],
    physicalResistance: 115,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 100,
      dark: 100,
    },
  },
  knight: {
    id: 0x02,
    name: "Knight",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["lawful", "neutral"],
    weatherResistance: 2,
    weightPenalty: 45,
    preferredWeaponCategory: "sword",
    movementTypes: ["fast"],
    physicalResistance: 110,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 95,
      dark: 105,
    },
  },
  berzerker: {
    id: 0x03,
    name: "Berzerker",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["neutral", "chaotic"],
    weatherResistance: 2,
    weightPenalty: 45,
    preferredWeaponCategory: "axe",
    movementTypes: ["fast"],
    physicalResistance: 105,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 105,
      dark: 95,
    },
  },
  terrorKnight: {
    id: 0x04,
    name: "Terror Knight",
    species: "human",
    allowedAlignments: ["chaotic"],
    allowedGenders: ["male"],
    weatherResistance: 2,
    weightPenalty: 50,
    preferredWeaponCategory: "axe",
    movementTypes: ["fast"],
    physicalResistance: 100,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 115,
      dark: 95,
    },
  },
  swordMaster: {
    id: 0x05,
    name: "Sword Master",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["lawful"],
    weatherResistance: 2,
    weightPenalty: 45,
    preferredWeaponCategory: "sword",
    movementTypes: ["fast"],
    physicalResistance: 120,
    baseResistances: {
      wind: 95,
      fire: 95,
      earth: 95,
      water: 95,
      holy: 85,
      dark: 100,
    },
    specialTraits: ["attack-plus"],
    indirectAttack: "accuse"
  },
  dragoon: {
    id: 0x06,
    name: "Dragoon",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["neutral"],
    weatherResistance: 2,
    weightPenalty: 45,
    preferredWeaponCategory: "sword",
    movementTypes: ["fast"],
    physicalResistance: 110,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 95,
      dark: 105,
    },
  },
  ninja: {
    id: 0x07,
    name: "Ninja",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["lawful", "neutral", "chaotic"],
    weatherResistance: 2,
    weightPenalty: 35,
    preferredWeaponCategory: "claw",
    movementTypes: ["fast-acrobatic", "on-water"],
    physicalResistance: 130,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 100,
      dark: 100,
    },
    specialTraits: ["attack-plus"],
    indirectAttack: "shuriken"
  },
  beastTamer: {
    id: 0x08,
    name: "Beast Tamer",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["lawful", "neutral", "chaotic"],
    weatherResistance: 2,
    weightPenalty: 45,
    preferredWeaponCategory: "whip",
    movementTypes: ["fast"],
    physicalResistance: 105,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 100,
      dark: 100,
    },
  },
  wizard: {
    id: 0x09,
    name: "Wizard",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["neutral", "chaotic"],
    weatherResistance: 2,
    weightPenalty: 50,
    movementTypes: ["slow"],
    physicalResistance: 125,
    baseResistances: {
      wind: 95,
      fire: 95,
      earth: 95,
      water: 95,
      holy: 95,
      dark: 95,
    },
  },
  warlock: {
    id: 0x0A,
    name: "Warlock",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["lawful", "neutral"],
    weatherResistance: 2,
    weightPenalty: 55,
    movementTypes: ["slow"],
    physicalResistance: 105,
    baseResistances: {
      wind: 90,
      fire: 90,
      earth: 90,
      water: 90,
      holy: 90,
      dark: 90,
    },
  },
  exorcist: {
    id: 0x0B,
    name: "Exorcist",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["lawful"],
    weatherResistance: 2,
    weightPenalty: 50,
    movementTypes: ["slow"],
    physicalResistance: 120,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 60,
      dark: 115,
    },
  },
  lich: {
    id: 0x0C,
    name: "Lich",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["lawful", "neutral", "chaotic"],
    weatherResistance: 2,
    weightPenalty: 50,
    movementTypes: ["slow"],
    physicalResistance: 65,
    baseResistances: {
      wind: 70,
      fire: 70,
      earth: 70,
      water: 70,
      holy: 85,
      dark: 85,
    },
  },
  gunner: {
    id: 0x0D,
    name: "Gunner",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["neutral"],
    weatherResistance: 0,
    weightPenalty: 75,
    preferredWeaponCategory: "gun",
    movementTypes: ["fast"],
    physicalResistance: 135,
    baseResistances: {
      wind: 130,
      fire: 130,
      earth: 130,
      water: 130,
      holy: 130,
      dark: 130,
    },
  },
  amazon: {
    id: 0x0E,
    name: "Amazon",
    species: "human",
    allowedGenders: ["female"],
    allowedAlignments: ["lawful", "neutral", "chaotic"],
    weatherResistance: 4,
    weightPenalty: 40,
    movementTypes: ["fast", "underwater"],
    physicalResistance: 115,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 100,
      dark: 100,
    },
  },
  valkyrie: {
    id: 0x0F,
    name: "Valkyrie",
    species: "human",
    allowedGenders: ["female"],
    allowedAlignments: ["lawful", "neutral"],
    weatherResistance: 4,
    weightPenalty: 45,
    preferredWeaponCategory: "spear",
    movementTypes: ["fast", "underwater"],
    physicalResistance: 110,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 95,
      dark: 105,
    },
  },
  archer: {
    id: 0x10,
    name: "Archer",
    species: "human",
    allowedGenders: ["female"],
    allowedAlignments: ["neutral", "chaotic"],
    weatherResistance: 4,
    weightPenalty: 35,
    preferredWeaponCategory: "bow",
    movementTypes: ["fast", "underwater"],
    physicalResistance: 110,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 100,
      dark: 95,
    },
  },
  dragonTamer: {
    id: 0x11,
    name: "Dragon Tamer",
    species: "human",
    allowedGenders: ["female"],
    allowedAlignments: ["lawful", "neutral", "chaotic"],
    weatherResistance: 4,
    weightPenalty: 45,
    preferredWeaponCategory: "sword",
    movementTypes: ["fast", "underwater"],
    physicalResistance: 110,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 100,
      dark: 100,
    },
  },
  siren: {
    id: 0x12,
    name: "Siren",
    species: "human",
    allowedGenders: ["female"],
    allowedAlignments: ["lawful", "neutral"],
    weatherResistance: 2,
    weightPenalty: 55,
    preferredWeaponCategory: "fan",
    movementTypes: ["slow"],
    physicalResistance: 120,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 80,
      dark: 80,
    },
  },
  witch: {
    id: 0x13,
    name: "Witch",
    species: "human",
    allowedGenders: ["female"],
    allowedAlignments: ["neutral", "chaotic"],
    weatherResistance: 2,
    weightPenalty: 50,
    movementTypes: ["fast"],
    physicalResistance: 125,
    baseResistances: {
      wind: 95,
      fire: 95,
      earth: 95,
      water: 95,
      holy: 100,
      dark: 90,
    },
  },
  cleric: {
    id: 0x14,
    name: "Cleric",
    species: "human",
    allowedGenders: ["female"],
    allowedAlignments: ["lawful", "neutral"],
    weatherResistance: 2,
    weightPenalty: 5,
    movementTypes: ["slow"],
    physicalResistance: 125,
    baseResistances: {
      wind: 95,
      fire: 95,
      earth: 95,
      water: 95,
      holy: 90,
      dark: 100,
    },
  },
  priest: {
    id: 0x15,
    name: "Priest",
    species: "human",
    allowedGenders: ["female"],
    allowedAlignments: ["lawful"],
    weatherResistance: 2,
    weightPenalty: 55,
    movementTypes: ["slow"],
    physicalResistance: 130,
    baseResistances: {
      wind: 90,
      fire: 90,
      earth: 90,
      water: 90,
      holy: 70,
      dark: 115,
    },
  },
  angelKnight: {
    id: 0x16,
    name: "Angel Knight",
    species: "human",
    allowedGenders: ["female"],
    allowedAlignments: ["lawful"],
    weatherResistance: 0,
    weightPenalty: 45,
    movementTypes: ["fly"],
    physicalResistance: 100,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 50,
      dark: 125,
    },
    preferredWeaponCategory: "spear"
  },
  faerie: {
    id: 0x17,
    name: "Faerie",
    species: "human",
    allowedGenders: ["female"],
    allowedAlignments: ["lawful", "neutral", "chaotic"],
    weatherResistance: 0,
    weightPenalty: 30,
    movementTypes: ["fly", "float"],
    physicalResistance: 125,
    baseResistances: {
      wind: 90,
      fire: 90,
      earth: 90,
      water: 90,
      holy: 90,
      dark: 90,
    },
  },
  gremlin: {
    id: 0x18,
    name: "Gremlin",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["lawful", "neutral", "chaotic"],
    weatherResistance: 0,
    weightPenalty: 45,
    movementTypes: ["fly", "float"],
    physicalResistance: 115,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 125,
      dark: 75,
    },
  },
  hawkMan: {
    id: 0x19,
    name: "Hawk Man",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["lawful", "neutral", "chaotic"],
    weatherResistance: 0,
    weightPenalty: 40,
    movementTypes: ["fly"],
    physicalResistance: 120,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 100,
      dark: 100,
    },
    preferredWeaponCategory: "axe"
  },
  lizardMan: {
    id: 0x1A,
    name: "Lizard Man",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["lawful", "neutral", "chaotic"],
    weatherResistance: 4,
    weightPenalty: 45,
    movementTypes: ["fast", "underwater"],
    physicalResistance: 105,
    baseResistances: {
      wind: 110,
      fire: 110,
      earth: 110,
      water: 110,
      holy: 110,
      dark: 110,
    },
    preferredWeaponCategory: "hammer"
  },
  pumpkinHead: {
    id: 0x1B,
    name: "Pumpkin Head",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["lawful", "neutral", "chaotic"],
    weatherResistance: 2,
    weightPenalty: 45,
    movementTypes: ["fast"],
    physicalResistance: 110,
    baseResistances: {
      wind: 95,
      fire: 95,
      earth: 95,
      water: 95,
      holy: 95,
      dark: 84,
    },
  },
  skeleton: {
    id: 0x1C,
    name: "Skeleton",
    species: "human",
    allowedGenders: ["male", "female"],
    allowedAlignments: ["lawful", "neutral", "chaotic"],
    weatherResistance: 2,
    weightPenalty: 40,
    movementTypes: ["fast"],
    physicalResistance: 110,
    baseResistances: {
      wind: 100,
      fire: 100,
      earth: 100,
      water: 100,
      holy: 125,
      dark: 75,
    },
  },
  ghost: {
    id: 0x1D,
    name: "Ghost",
    species: "human",
    allowedGenders: ["male", "female"],
    allowedAlignments: ["lawful", "neutral", "chaotic"],
    weatherResistance: 4,
    weightPenalty: 45,
    movementTypes: ["warp", "float"],
    physicalResistance: 65,
    baseResistances: {
      wind: 110,
      fire: 110,
      earth: 110,
      water: 110,
      holy: 135,
      dark: 85,
    },
  },
  templarKnight: {
    id: 0x1E,
    name: "Templar Knight",
    species: "human",
    allowedGenders: ["male"],
    allowedAlignments: ["lawful", "neutral", "chaotic"],
    weatherResistance: 2,
    weightPenalty: 45,
    movementTypes: ["fast"],
    physicalResistance: 105,
    baseResistances: {
      wind: 95,
      fire: 95,
      earth: 95,
      water: 95,
      holy: 90,
      dark: 90,
    },
  },
}