import {
  type WeaponStats,
  type ArmorStats,
  type ConsumableStats,
} from "@/utils/combat"

export const ITEM_CATALOG: (WeaponStats | ArmorStats | ConsumableStats)[] = [
  // Weapons
  {
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Mini Dagger",
    strength: 12,
    weight: 3,
    iconName: "mini",
    handsRequired: 1,
  },
  {
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Short Sword",
    strength: 15,
    weight: 7,
    iconName: "short",
    handsRequired: 1,
  },
  {
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Balder Dagger",
    strength: 25,
    weight: 24,
    iconName: "balderkn",
    handsRequired: 1,
    statModifiers: { intelligence: 5 },
  },
  {
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Balder Sword",
    strength: 30,
    weight: 31,
    iconName: "baldersd",
    handsRequired: 1,
    statModifiers: { intelligence: 5 },
  },
  {
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Fire Sword",
    strength: 32,
    weight: 32,
    iconName: "firesd",
    element: "fire",
    handsRequired: 1,
    elementalResistances: { water: 5 },
  },
  {
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Phlanka Axe",
    strength: 16,
    weight: 8,
    iconName: "phlanka",
    handsRequired: 1,
  },
  {
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Spear",
    strength: 12,
    weight: 9,
    iconName: "spear",
    handsRequired: 2,
  },
  {
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Slender Spear",
    strength: 22,
    weight: 23,
    iconName: "slender",
    handsRequired: 2,
  },
  {
    type: "weapon",
    slot: "hands",
    category: "hammer",
    name: "Heavy Hammer",
    strength: 18,
    weight: 14,
    iconName: "heavyhm",
    handsRequired: 1,
  },
  {
    type: "weapon",
    slot: "hands",
    category: "hammer",
    name: "Aqua Hammer",
    strength: 29,
    weight: 32,
    iconName: "aquahm",
    element: "water",
    handsRequired: 1,
    elementalResistances: { fire: 5 }
  },
  {
    type: "weapon",
    slot: "hands",
    category: "claw",
    name: "Matou",
    strength: 24,
    weight: 21,
    iconName: "matou",
    handsRequired: 1,
  },
  {
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Cedar Staff",
    strength: 6,
    weight: 2,
    iconName: "cedar",
    handsRequired: 1,
    statModifiers: { intelligence: 10 }
  },
  {
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Clear Staff",
    strength: 7,
    weight: 4,
    iconName: "clearst",
    handsRequired: 1,
    statModifiers: { intelligence: 14, mentality: 4 }
  },
  {
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Life Staff",
    strength: 7,
    weight: 4,
    iconName: "lifest",
    handsRequired: 1,
    statModifiers: { intelligence: 14, mentality: 4 }
  },
  {
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Balder Staff",
    strength: 7,
    weight: 7,
    iconName: "balderst",
    handsRequired: 1,
    statModifiers: { intelligence: 18 }
  },
  {
    type: "weapon",
    slot: "hands",
    category: "whip",
    name: "Guard Whip",
    strength: 24,
    weight: 25,
    iconName: "guardwh",
    handsRequired: 2,
  },
  {
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Short Bow",
    strength: 10,
    weight: 6,
    iconName: "shortbw",
    handsRequired: 1,
  },
  {
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Great Bow",
    strength: 15,
    weight: 15,
    iconName: "greatbw",
    handsRequired: 2,
  },
  {
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Balder Bow",
    strength: 21,
    weight: 32,
    iconName: "balderbw",
    handsRequired: 2,
    statModifiers: { intelligence: 5 }
  },
  {
    type: "weapon",
    slot: "hands",
    category: "crossbow",
    name: "Crossbow",
    strength: 15,
    weight: 24,
    iconName: "crossbow",
    handsRequired: 1,
  },
  {
    type: "weapon",
    slot: "hands",
    category: "crossbow",
    name: "Gemini Crossbow",
    strength: 23,
    weight: 36,
    iconName: "gemini",
    handsRequired: 2,
  },
  // Armor
  {
    type: "armor",
    name: "Leather Armor",
    physicalResistance: 3,
    weight: 6,
    iconName: "leatherar",
    slot: "body",
    handsRequired: 0,
  },
  {
    type: "armor",
    name: "Chain Mail",
    physicalResistance: 6,
    weight: 12,
    iconName: "chainar",
    slot: "body",
    handsRequired: 0,
  },
  {
    type: "armor",
    name: "Balder Armor",
    physicalResistance: 9,
    weight: 18,
    iconName: "balderar",
    slot: "body",
    handsRequired: 0,
    statModifiers: { intelligence: 5 }
  },
  {
    type: "armor",
    name: "Robe",
    physicalResistance: 1,
    weight: 1,
    iconName: "robe",
    slot: "body",
    handsRequired: 0,
  },
  {
    type: "armor",
    name: "Balder Robe",
    physicalResistance: 4,
    weight: 3,
    iconName: "balderrb",
    slot: "body",
    handsRequired: 0,
    statModifiers: { intelligence: 5 }
  },
  {
    type: "armor",
    name: "Leather Cap",
    physicalResistance: 2,
    weight: 4,
    iconName: "leatherht",
    slot: "head",
    handsRequired: 0,
  },
  {
    type: "armor",
    name: "Balder Helmet",
    physicalResistance: 6,
    weight: 12,
    iconName: "balderht",
    slot: "head",
    handsRequired: 0,
    statModifiers: { intelligence: 5 }
  },
  {
    type: "armor",
    name: "Battle Boots",
    physicalResistance: 4,
    weight: 7,
    iconName: "battlebt",
    slot: "feet",
    handsRequired: 0,
    statModifiers: { agility: 4 }
  },
  {
    type: "armor",
    name: "Tower Shield",
    physicalResistance: 10,
    weight: 10,
    iconName: "tower",
    slot: "hands",
    handsRequired: 1,
  },
  {
    type: "armor",
    name: "Balder Shield",
    physicalResistance: 15,
    weight: 20,
    iconName: "baldersh",
    slot: "hands",
    handsRequired: 1,
    statModifiers: { intelligence: 5 }
  },
  {
    type: "armor",
    name: "Power Gauntlet",
    physicalResistance: 10,
    weight: 10,
    iconName: "powergt",
    slot: "hands",
    handsRequired: 1,
    statModifiers: { strength: 5 }
  },
  {
    type: "armor",
    name: "Balder Gauntlet",
    physicalResistance: 13,
    weight: 16,
    iconName: "baldergt",
    slot: "hands",
    handsRequired: 1,
  },
  {
    type: "armor",
    name: "Magic Ring",
    physicalResistance: 0,
    weight: 1,
    iconName: "magicrg",
    slot: "hands",
    handsRequired: 0,
  },
  {
    type: "armor",
    name: "Mind Ring",
    physicalResistance: 0,
    weight: 1,
    iconName: "mindrg",
    slot: "hands",
    handsRequired: 0,
  },
  {
    type: "consumable",
    name: "Cure",
    weight: 1,
    iconName: "cure",
    slot: "bag",
    handsRequired: 0,
  },
  {
    type: "consumable",
    name: "Cure+",
    weight: 1,
    iconName: "cure2",
    slot: "bag",
    handsRequired: 0,
  },
  {
    type: "consumable",
    name: "Antidote",
    weight: 1,
    iconName: "antidote",
    slot: "bag",
    handsRequired: 0,
  },
]
