import { type EquippableItem } from "@/utils/combat"

export const ITEM_CATALOG: EquippableItem[] = [
  // Weapons
  {
    key: "punch",
    type: "weapon",
    name: "Punch",
    slot: null,
    category: "claw",
    strength: 0,
    weight: 0,
    handsRequired: 0,
    multiplier: 0.5,
  },
  {
    key: "stone",
    type: "weapon",
    name: "Stone",
    slot: null,
    category: "bow",
    strength: 0,
    weight: 0,
    handsRequired: 0,
    multiplier: 0.25,
  },
  {
    key: "warriorsd",
    type: "weapon",
    name: "Warrior",
    slot: "hands",
    category: "sword",
    strength: 1,
    weight: 52,
    handsRequired: 1,
    description: "LUK+1 at lvl. up",
  },
  {
    key: "mini",
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Mini",
    strength: 12,
    weight: 3,
    handsRequired: 1,
  },
  {
    key: "short",
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Short",
    strength: 15,
    weight: 7,
    handsRequired: 1,
  },
  {
    key: "balderkn",
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Balder",
    strength: 25,
    weight: 24,
    handsRequired: 1,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "desert",
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Desert",
    strength: 28,
    weight: 18,
    handsRequired: 1,
    statModifiers: { dexterity: 5 },
    description: "Petrify resist ",
  },
  {
    key: "baldersd",
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Balder",
    strength: 30,
    weight: 31,
    handsRequired: 1,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "isleberg",
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Isleberg",
    strength: 30,
    weight: 22,
    handsRequired: 2,
    statModifiers: { dexterity: 5 },
    description: "Stun resist",
  },
  {
    key: "icesd",
    type: "weapon",
    name: "Ice",
    slot: "hands",
    category: "sword",
    strength: 31,
    weight: 35,
    element: "water",
    handsRequired: 1,
    elementalResistances: { fire: 5 },
  },
  {
    key: "firesd",
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Fire",
    strength: 32,
    weight: 32,
    element: "fire",
    handsRequired: 1,
    elementalResistances: { water: 5 },
    antiDragon: true,
  },
  {
    key: "angelsd",
    type: "weapon",
    name: "Angel",
    slot: "hands",
    category: "sword",
    strength: 32,
    weight: 23,
    element: "holy",
    handsRequired: 1,
    elementalResistances: { dark: 5 },
  },
  {
    key: "granitesd",
    type: "weapon",
    name: "Granite",
    slot: "hands",
    category: "sword",
    strength: 33,
    weight: 37,
    element: "earth",
    handsRequired: 1,
    elementalResistances: { wind: 5 },
  },
  {
    key: "fafniel",
    type: "weapon",
    name: "Fafniel",
    slot: "hands",
    category: "sword",
    strength: 33,
    weight: 37,
    handsRequired: 1,
    antiDragon: true,
  },
  {
    key: "penetent",
    type: "weapon",
    name: "Penetent",
    slot: "hands",
    category: "sword",
    strength: 34,
    weight: 28,
    handsRequired: 1,
    element: "holy",
    elementalResistances: { dark: 5 },
  },
  {
    key: "dragonsd",
    type: "weapon",
    name: "Dragon",
    slot: "hands",
    category: "sword",
    strength: 35,
    weight: 37,
    handsRequired: 2,
    antiDragon: true,
  },
  {
    key: "nyfret",
    type: "weapon",
    name: "Nyfret",
    slot: "hands",
    category: "sword",
    strength: 35,
    weight: 20,
    handsRequired: 1,
    element: "water",
    elementalResistances: { fire: 5 },
  },
  {
    key: "zenobia",
    type: "weapon",
    name: "Zenobia",
    slot: "hands",
    category: "sword",
    strength: 35,
    weight: 20,
    handsRequired: 1,
    statModifiers: { mentality: 4 },
    description: "Ailment resist",
  },
  {
    key: "ogresd",
    type: "weapon",
    name: "Ogre",
    slot: "hands",
    category: "sword",
    strength: 36,
    weight: 42,
    handsRequired: 1,
    element: "dark",
    elementalResistances: { holy: 10, dark: -5 },
    description: "Body Grab",
  },
  {
    key: "notos",
    type: "weapon",
    name: "Notos",
    slot: "hands",
    category: "sword",
    strength: 40,
    weight: 40,
    handsRequired: 2,
    element: "wind",
    elementalResistances: { earth: 5 },
  },
  {
    key: "balmuck",
    type: "weapon",
    name: "Balmuck",
    slot: "hands",
    category: "sword",
    strength: 42,
    weight: 43,
    handsRequired: 2,
  },
  {
    key: "oricon",
    type: "weapon",
    name: "Oricon",
    slot: "hands",
    category: "sword",
    strength: 45,
    weight: 39,
    handsRequired: 1,
    element: "holy",
    elementalResistances: { dark: 10, holy: -5 },
    description: "Jihad",
  },
  {
    key: "brunhild",
    type: "weapon",
    name: "Brunhild",
    slot: "hands",
    category: "sword",
    strength: 50,
    weight: 36,
    handsRequired: 1,
    element: "holy",
    elementalResistances: { dark: 15, holy: -10 },
  },
  /* {
    key: "firesn",
    type: "weapon",
    name: "Fire",
    slot: "hands",
    category: "sword",
    strength: 0,
    weight: 0,
    handsRequired: 1,
    element: "fire",
  },
  {
    key: "earthsn",
    type: "weapon",
    name: "Earth",
    slot: "hands",
    category: "sword",
    strength: 0,
    weight: 0,
    handsRequired: 1,
    element: "earth",
  },
  {
    key: "watersn",
    type: "weapon",
    name: "Water",
    slot: "hands",
    category: "sword",
    strength: 0,
    weight: 0,
    handsRequired: 1,
    element: "water",
  },
  {
    key: "windsn",
    type: "weapon",
    name: "Wind",
    slot: "hands",
    category: "sword",
    strength: 0,
    weight: 0,
    handsRequired: 1,
    element: "wind",
  },
  {
    key: "holysn",
    type: "weapon",
    name: "Holy",
    slot: "hands",
    category: "sword",
    strength: 0,
    weight: 0,
    handsRequired: 1,
    element: "holy",
  },
  {
    key: "shadowsn",
    type: "weapon",
    name: "Shadow",
    slot: "hands",
    category: "sword",
    strength: 0,
    weight: 0,
    handsRequired: 1,
    element: "dark",
  }, */
  {
    key: "phlanka",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Phlanka Axe",
    strength: 16,
    weight: 8,
    handsRequired: 1,
  },
  {
    key: "gramrock",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Gramrock",
    strength: 32,
    weight: 30,
    handsRequired: 2,
    element: "fire",
    elementalResistances: { water: 5 },
  },
  {
    key: "iceax",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Ice",
    strength: 33,
    weight: 31,
    handsRequired: 2,
    element: "water",
    elementalResistances: { fire: 5 },
  },
  {
    key: "earthax",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Gramrock",
    strength: 34,
    weight: 30,
    handsRequired: 2,
    element: "earth",
    elementalResistances: { wind: 5 },
    antiDragon: true,
  },
  {
    key: "balderax",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Balder",
    strength: 34,
    weight: 34,
    handsRequired: 2,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "procs",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Procs",
    strength: 36,
    weight: 37,
    handsRequired: 2,
    element: "fire",
    elementalResistances: { water: 5 },
  },
  {
    key: "boleas",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Boleas",
    strength: 40,
    weight: 42,
    handsRequired: 2,
    element: "wind",
    elementalResistances: { earth: 5 },
  },
  {
    key: "runeax",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Rune",
    strength: 42,
    weight: 43,
    handsRequired: 2,
    element: "holy",
    elementalResistances: { dark: 5 },
  },
  {
    key: "heavyax",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Heavy",
    strength: 45,
    weight: 49,
    handsRequired: 2,
  },
  {
    key: "bloodax",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Blood",
    strength: 48,
    weight: 51,
    handsRequired: 2,
    element: "dark",
    elementalResistances: { holy: 10 },
    description: "Life Suck",
  },
  {
    key: "spear",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Spear",
    strength: 12,
    weight: 9,
    handsRequired: 2,
  },
  {
    key: "slender",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Slender",
    strength: 22,
    weight: 23,
    handsRequired: 2,
  },
  {
    key: "herosp",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Hero",
    strength: 31,
    weight: 37,
    handsRequired: 2,
    element: "water",
    elementalResistances: { fire: 5 },
  },
  {
    key: "volcano",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Volcano",
    strength: 32,
    weight: 38,
    handsRequired: 2,
    element: "fire",
    elementalResistances: { water: 5 },
  },
  {
    key: "baldersp",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Balder",
    strength: 32,
    weight: 38,
    handsRequired: 2,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "earthsp",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Earth",
    strength: 34,
    weight: 36,
    handsRequired: 2,
    element: "earth",
    elementalResistances: { wind: 5 },
  },
  {
    key: "zepyulos",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Zepyulos",
    strength: 35,
    weight: 40,
    handsRequired: 2,
    element: "wind",
    elementalResistances: { earth: 5 },
  },
  {
    key: "unicorn",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Unicorn",
    strength: 42,
    weight: 52,
    handsRequired: 2,
    statModifiers: { intelligence: 9, luck: 4 },
  },
  {
    key: "evilsp",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Evil",
    strength: 43,
    weight: 51,
    handsRequired: 2,
    element: "dark",
    elementalResistances: { holy: 5 },
  },
  {
    key: "igunis",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Igunis",
    strength: 45,
    weight: 35,
    handsRequired: 2,
    element: "fire",
    elementalResistances: { water: 5 },
  },
  {
    key: "holysp",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Holy",
    strength: 45,
    weight: 54,
    handsRequired: 2,
    element: "holy",
    elementalResistances: { dark: 5 },
  },
  {
    key: "heavyhm",
    type: "weapon",
    slot: "hands",
    category: "hammer",
    name: "Heavy",
    strength: 18,
    weight: 14,
    handsRequired: 1,
  },
  {
    key: "aquahm",
    type: "weapon",
    slot: "hands",
    category: "hammer",
    name: "Aqua",
    strength: 29,
    weight: 32,
    element: "water",
    handsRequired: 1,
    elementalResistances: { fire: 5 },
  },
  {
    key: "balderhm",
    type: "weapon",
    slot: "hands",
    category: "hammer",
    name: "Balder",
    strength: 30,
    weight: 31,
    handsRequired: 2,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "eros",
    type: "weapon",
    slot: "hands",
    category: "hammer",
    name: "Eros",
    strength: 30,
    weight: 32,
    element: "wind",
    handsRequired: 1,
    elementalResistances: { earth: 5 },
  },
  {
    key: "flamehm",
    type: "weapon",
    slot: "hands",
    category: "hammer",
    name: "Flame",
    strength: 31,
    weight: 35,
    element: "fire",
    handsRequired: 1,
    elementalResistances: { water: 5 },
  },
  {
    key: "lighthm",
    type: "weapon",
    slot: "hands",
    category: "hammer",
    name: "Light",
    strength: 32,
    weight: 36,
    element: "holy",
    handsRequired: 1,
    elementalResistances: { dark: 5 },
  },
  {
    key: "phalanx",
    type: "weapon",
    slot: "hands",
    category: "hammer",
    name: "Phalanx",
    strength: 34,
    weight: 37,
    element: "earth",
    handsRequired: 1,
    elementalResistances: { wind: 5 },
  },
  {
    key: "earthhm",
    type: "weapon",
    slot: "hands",
    category: "hammer",
    name: "Earth",
    strength: 38,
    weight: 31,
    element: "earth",
    handsRequired: 1,
    elementalResistances: { wind: 5 },
  },
  {
    key: "powerhm",
    type: "weapon",
    slot: "hands",
    category: "hammer",
    name: "Power",
    strength: 44,
    weight: 46,
    handsRequired: 2,
  },
  {
    key: "darkhm",
    type: "weapon",
    slot: "hands",
    category: "hammer",
    name: "Dark",
    strength: 48,
    weight: 51,
    element: "dark",
    handsRequired: 2,
    elementalResistances: { holy: 5 },
  },
  {
    key: "matou",
    type: "weapon",
    slot: "hands",
    category: "claw",
    name: "Matou",
    strength: 24,
    weight: 21,
    handsRequired: 1,
  },
  {
    key: "thundercw",
    type: "weapon",
    slot: "hands",
    category: "claw",
    name: "Thunder",
    strength: 26,
    weight: 27,
    handsRequired: 1,
    element: "wind",
    elementalResistances: { earth: 5 },
  },
  {
    key: "bluecw",
    type: "weapon",
    slot: "hands",
    category: "claw",
    name: "Blue",
    strength: 31,
    weight: 35,
    handsRequired: 1,
    antiDragon: true,
  },
  {
    key: "catcw",
    type: "weapon",
    slot: "hands",
    category: "claw",
    name: "Cat",
    strength: 35,
    weight: 40,
    handsRequired: 1,
    element: "dark",
    elementalResistances: { holy: 5 },
    statModifiers: { luck: -5 },
    description: "Poisons target",
  },
  {
    key: "galdia",
    type: "weapon",
    slot: "hands",
    category: "fan",
    name: "Galdia",
    strength: 23,
    weight: 24,
    handsRequired: 1,
    element: "holy",
    elementalResistances: { dark: 5 },
    statModifiers: { luck: 4, agility: 8 },
    description: "Charms target",
  },
  {
    key: "cedar",
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Cedar",
    strength: 6,
    weight: 2,
    handsRequired: 1,
    statModifiers: { intelligence: 10 },
  },
  {
    key: "poisonst",
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Poison",
    strength: 6,
    weight: 9,
    handsRequired: 1,
    element: "water",
    statModifiers: { intelligence: 20 },
    elementalResistances: { fire: 5 },
    description: "Hazard",
  },
  {
    key: "clearst",
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Clear",
    strength: 7,
    weight: 4,
    handsRequired: 1,
    statModifiers: { intelligence: 14, mentality: 4 },
    description: "Remedy",
  },
  {
    key: "lifest",
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Life",
    strength: 7,
    weight: 4,
    handsRequired: 1,
    statModifiers: { intelligence: 14, mentality: 4 },
    description: "50 Heal",
  },
  {
    key: "balderst",
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Balder",
    strength: 7,
    weight: 7,
    handsRequired: 1,
    statModifiers: { intelligence: 18 },
  },
  {
    key: "windst",
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Wind",
    strength: 8,
    weight: 9,
    handsRequired: 1,
    element: "wind",
    statModifiers: { intelligence: 19 },
    elementalResistances: { earth: 5 },
    description: "Wind Shot",
  },
  {
    key: "firest",
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Fire",
    strength: 9,
    weight: 9,
    handsRequired: 1,
    element: "fire",
    statModifiers: { intelligence: 17 },
    elementalResistances: { water: 5 },
    description: "Glow Ball",
  },
  {
    key: "earthst",
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Earth",
    strength: 9,
    weight: 10,
    handsRequired: 1,
    element: "earth",
    statModifiers: { intelligence: 18 },
    elementalResistances: { wind: 5 },
    description: "X-Zone",
  },
  {
    key: "chargest",
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Charge",
    strength: 10,
    weight: 13,
    handsRequired: 1,
    statModifiers: { intelligence: 25, mentality: 8 },
    description: "25 MP",
  },
  {
    key: "ripplest",
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Ripple",
    strength: 10,
    weight: 14,
    handsRequired: 1,
    element: "holy",
    statModifiers: { intelligence: 30 },
    elementalResistances: { dark: 5 },
    description: "Holy Bolt",
  },
  {
    key: "dragonst",
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Dragon",
    strength: 11,
    weight: 12,
    handsRequired: 1,
    element: "dark",
    statModifiers: { intelligence: 16 },
    elementalResistances: { holy: 5 },
    description: "Abyss",
  },
  {
    key: "guardwh",
    type: "weapon",
    slot: "hands",
    category: "whip",
    name: "Guard",
    strength: 24,
    weight: 25,
    handsRequired: 2,
  },
  {
    key: "cometwh",
    type: "weapon",
    slot: "hands",
    category: "whip",
    name: "Comet",
    strength: 31,
    weight: 35,
    handsRequired: 2,
    element: "holy",
    elementalResistances: { dark: 5 },
  },
  {
    key: "rosebud",
    type: "weapon",
    slot: "hands",
    category: "whip",
    name: "Rosebud",
    strength: 33,
    weight: 30,
    handsRequired: 2,
    element: "dark",
    elementalResistances: { holy: 5 },
  },
  {
    key: "bloodwh",
    type: "weapon",
    slot: "hands",
    category: "whip",
    name: "Blood",
    strength: 40,
    weight: 34,
    handsRequired: 2,
    element: "dark",
    elementalResistances: { holy: 5 },
  },
  {
    key: "rimfire",
    type: "weapon",
    slot: "hands",
    name: "RimFire",
    category: "gun",
    strength: 7,
    weight: 22,
    handsRequired: 1,
  },
  {
    key: "shotgun",
    type: "weapon",
    slot: "hands",
    name: "Shotgun",
    category: "gun",
    strength: 9,
    weight: 37,
    handsRequired: 2,
  },
  {
    key: "rifle",
    type: "weapon",
    slot: "hands",
    name: "Rifle",
    category: "gun",
    strength: 11,
    weight: 52,
    handsRequired: 2,
  },
  {
    key: "shortbw",
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Short",
    strength: 10,
    weight: 6,
    handsRequired: 1,
  },
  {
    key: "greatbw",
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Great",
    strength: 15,
    weight: 15,
    handsRequired: 2,
  },
  {
    key: "balderbw",
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Balder",
    strength: 21,
    weight: 32,
    handsRequired: 2,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "sandbw",
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Sand",
    strength: 24,
    weight: 32,
    handsRequired: 2,
    element: "earth",
    elementalResistances: { wind: 5 },
  },
  {
    key: "lightbw",
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Light",
    strength: 25,
    weight: 32,
    handsRequired: 2,
    element: "wind",
    elementalResistances: { earth: 5 },
  },
  {
    key: "firebw",
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Fire",
    strength: 26,
    weight: 36,
    handsRequired: 2,
    element: "fire",
    elementalResistances: { water: 5 },
  },
  {
    key: "icebw",
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Ice",
    strength: 27,
    weight: 39,
    handsRequired: 2,
    element: "water",
    elementalResistances: { fire: 5 },
  },
  {
    key: "starbw",
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Star",
    strength: 30,
    weight: 42,
    handsRequired: 2,
    element: "holy",
    statModifiers: { dexterity: 8 },
    elementalResistances: { dark: 5 },
    description: "Stuns target",
  },
  {
    key: "chaosbw",
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Chaos",
    strength: 30,
    weight: 41,
    handsRequired: 2,
    element: "dark",
    statModifiers: { strength: 5 },
    elementalResistances: { holy: 5 },
    description: "Charms target",
  },
  {
    key: "darkwb",
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Dark",
    strength: 34,
    weight: 54,
    handsRequired: 2,
    element: "dark",
    elementalResistances: { holy: 10 },
    description: "Petrifies target",
  },
  {
    key: "crossbow",
    name: "Crossbow",
    type: "weapon",
    slot: "hands",
    category: "crossbow",
    strength: 15,
    weight: 24,
    handsRequired: 1,
  },
  {
    key: "gemini",
    type: "weapon",
    name: "Gemini",
    slot: "hands",
    category: "crossbow",
    strength: 23,
    weight: 36,
    handsRequired: 2,
  },
  {
    key: "saint",
    type: "weapon",
    name: "Saint",
    slot: "hands",
    category: "crossbow",
    strength: 30,
    weight: 49,
    handsRequired: 2,
    element: "holy",
    elementalResistances: { dark: 10 },
  },
  {
    key: "paragun",
    name: "Paragun",
    type: "weapon",
    slot: "hands",
    category: "blowgun",
    strength: 16,
    weight: 24,
    handsRequired: 1,
    description: "Sleeps target",
  },
  // Armor
  {
    key: "warriorar",
    type: "armor",
    name: "Warrior",
    physicalResistance: 1,
    weight: 25,
    slot: "body",
    handsRequired: 0,
    description: "LUK+1 at lv. up",
  },
  {
    key: "leatherar",
    type: "armor",
    name: "Leather",
    physicalResistance: 3,
    weight: 6,
    slot: "body",
    handsRequired: 0,
  },
  {
    key: "chainar",
    type: "armor",
    name: "Chain",
    physicalResistance: 6,
    weight: 12,
    slot: "body",
    handsRequired: 0,
  },
  {
    key: "balderar",
    type: "armor",
    name: "Balder",
    physicalResistance: 9,
    weight: 18,
    slot: "body",
    handsRequired: 0,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "dragonar",
    type: "armor",
    name: "Dragon",
    physicalResistance: 10,
    weight: 20,
    slot: "body",
    handsRequired: 0,
  },
  {
    key: "faeriear",
    type: "armor",
    name: "Faerie",
    physicalResistance: 12,
    weight: 24,
    slot: "body",
    handsRequired: 0,
    statModifiers: { agility: 4 },
    description: "Ailment resist",
  },
  {
    key: "aquaar",
    type: "armor",
    name: "Aqua",
    physicalResistance: 13,
    weight: 28,
    slot: "body",
    handsRequired: 0,
    elementalResistances: { fire: 5 },
  },
  {
    key: "wingar",
    type: "armor",
    name: "Wing",
    physicalResistance: 13,
    weight: 28,
    slot: "body",
    handsRequired: 0,
    elementalResistances: { earth: 5 },
  },
  {
    key: "phoenixar",
    type: "armor",
    name: "Phoenix",
    physicalResistance: 13,
    weight: 28,
    slot: "body",
    handsRequired: 0,
    elementalResistances: { water: 5 },
  },
  {
    key: "granitear",
    type: "armor",
    name: "Granite",
    physicalResistance: 13,
    weight: 28,
    slot: "body",
    handsRequired: 0,
    elementalResistances: { wind: 5 },
  },
  {
    key: "grimar",
    type: "armor",
    name: "Grim",
    physicalResistance: 13,
    weight: 28,
    slot: "body",
    handsRequired: 0,
    elementalResistances: { holy: 15 },
  },
  {
    key: "angelar",
    type: "armor",
    name: "Angel",
    physicalResistance: 13,
    weight: 28,
    slot: "body",
    handsRequired: 0,
    elementalResistances: { dark: 15 },
    description: "HP regen",
  },
  {
    key: "ogrear",
    type: "armor",
    name: "Ogre",
    physicalResistance: 20,
    weight: 30,
    slot: "body",
    handsRequired: 0,
    elementalResistances: { holy: 20 },
  },
  {
    key: "robe",
    type: "armor",
    name: "Robe",
    physicalResistance: 1,
    weight: 1,
    slot: "body",
    handsRequired: 0,
  },
  {
    key: "balderrb",
    type: "armor",
    name: "Balder",
    physicalResistance: 4,
    weight: 3,
    slot: "body",
    handsRequired: 0,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "aquarb",
    type: "armor",
    name: "Aqua",
    physicalResistance: 5,
    weight: 5,
    slot: "body",
    handsRequired: 0,
    statModifiers: { intelligence: 5 },
    elementalResistances: { fire: 10 },
  },
  {
    key: "firerb",
    type: "armor",
    name: "Fire",
    physicalResistance: 5,
    weight: 5,
    slot: "body",
    handsRequired: 0,
    statModifiers: { intelligence: 5 },
    elementalResistances: { water: 10 },
  },
  {
    key: "soilrb",
    type: "armor",
    name: "Soil",
    physicalResistance: 5,
    weight: 5,
    slot: "body",
    handsRequired: 0,
    elementalResistances: { wind: 10 },
    statModifiers: { intelligence: 5 },
  },
  {
    key: "windrb",
    type: "armor",
    name: "Wind",
    physicalResistance: 5,
    weight: 5,
    slot: "body",
    handsRequired: 0,
    elementalResistances: { earth: 10 },
    statModifiers: { intelligence: 5 },
  },
  {
    key: "evilrb",
    type: "armor",
    name: "Evil",
    physicalResistance: 5,
    weight: 5,
    slot: "body",
    handsRequired: 0,
    elementalResistances: { holy: 10 },
    statModifiers: { intelligence: 10 },
    description: "MP regen",
  },
  {
    key: "holyrb",
    type: "armor",
    name: "Holy",
    physicalResistance: 5,
    weight: 5,
    slot: "body",
    handsRequired: 0,
    elementalResistances: { dark: 10 },
    statModifiers: { intelligence: 10 },
    description: "MP regen",
  },
  {
    key: "crystalrb",
    type: "armor",
    name: "Crystal",
    physicalResistance: 6,
    weight: 6,
    slot: "body",
    handsRequired: 0,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "warriorht",
    type: "armor",
    name: "Warrior",
    physicalResistance: 1,
    weight: 15,
    slot: "head",
    handsRequired: 0,
    description: "LUK+1 at lv. up",
  },
  {
    key: "leatherht",
    type: "armor",
    name: "Leather",
    physicalResistance: 2,
    weight: 4,
    slot: "head",
    handsRequired: 0,
  },
  {
    key: "balderht",
    type: "armor",
    name: "Balder",
    physicalResistance: 6,
    weight: 12,
    slot: "head",
    handsRequired: 0,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "holyht",
    type: "armor",
    name: "Holy",
    physicalResistance: 1,
    weight: 13,
    slot: "head",
    handsRequired: 0,
    elementalResistances: { dark: 5 },
  },
  {
    key: "dragonht",
    type: "armor",
    name: "Dragon",
    physicalResistance: 8,
    weight: 16,
    slot: "head",
    handsRequired: 0,
  },
  {
    key: "lightht",
    type: "armor",
    name: "Light",
    physicalResistance: 10,
    weight: 20,
    slot: "head",
    handsRequired: 0,
    elementalResistances: { dark: 10 },
  },
  {
    key: "ogreht",
    type: "armor",
    name: "Ogre",
    physicalResistance: 10,
    weight: 20,
    slot: "head",
    handsRequired: 0,
    elementalResistances: { holy: 10 },
  },
  {
    key: "vancharm",
    name: "VanCharm",
    type: "armor",
    slot: "head",
    physicalResistance: 0,
    weight: 1,
    handsRequired: 0,
    statModifiers: { mentality: 5, luck: 5 },
    elementalResistances: { earth: 5 },
    description: "+Wind power"
  },
  {
    key: "ohncharm",
    name: "OhnCharm",
    type: "armor",
    slot: "head",
    physicalResistance: 0,
    weight: 1,
    handsRequired: 0,
    statModifiers: { mentality: 5, luck: 5 },
    elementalResistances: { fire: 5 },
    description: "+Water power"
  },
  {
    key: "solcharm",
    name: "SolCharm",
    type: "armor",
    slot: "head",
    physicalResistance: 0,
    weight: 1,
    handsRequired: 0,
    statModifiers: { mentality: 5, luck: 5 },
    elementalResistances: { wind: 5 },
    description: "+Earth power"
  },
  {
    key: "folcharm",
    name: "FolCharm",
    type: "armor",
    slot: "head",
    physicalResistance: 0,
    weight: 1,
    handsRequired: 0,
    statModifiers: { mentality: 5, luck: 5 },
    elementalResistances: { water: 5 },
    description: "+Fire power"
  },
  {
    key: "bluenk",
    name: "Blue",
    type: "armor",
    physicalResistance: 0,
    weight: 1,
    slot: "head",
    handsRequired: 0,
    statModifiers: { mentality: 10 },
    elementalResistances: { dark: 5 },
    description: "Ailment resist",
  },
  {
    key: "rednk",
    name: "Red",
    type: "armor",
    physicalResistance: 0,
    weight: 1,
    slot: "head",
    handsRequired: 0,
    statModifiers: { mentality: 10 },
    elementalResistances: { dark: 5 },
    description: "Ailment resist",
  },
  {
    key: "blacknk",
    name: "Black",
    type: "armor",
    physicalResistance: 0,
    weight: 1,
    slot: "head",
    handsRequired: 0,
    statModifiers: { mentality: 10 },
    elementalResistances: { dark: 5 },
    description: "Magic resist",
  },
  {
    key: "evilnk",
    name: "Evil",
    type: "armor",
    physicalResistance: 0,
    weight: 1,
    slot: "head",
    handsRequired: 0,
    statModifiers: { mentality: 10 },
    elementalResistances: { holy: 5 },
    description: "Spreads fear",
  },
  {
    key: "sparkbt",
    name: "Spark",
    type: "armor",
    slot: "feet",
    handsRequired: 0,
    physicalResistance: 3,
    weight: 5,
    statModifiers: { agility: 4 },
    description: "Lava walk",
  },
  {
    key: "greasebt",
    name: "Grease",
    type: "armor",
    slot: "feet",
    handsRequired: 0,
    physicalResistance: 3,
    weight: 5,
    statModifiers: { agility: 4 },
    description: "Water walk",
  },
  {
    key: "warpbt",
    name: "Warp",
    type: "armor",
    slot: "feet",
    handsRequired: 0,
    physicalResistance: 3,
    weight: 5,
    statModifiers: { agility: 4 },
    description: "Warp move",
  },
  {
    key: "wingbt",
    name: "Wing",
    type: "armor",
    slot: "feet",
    handsRequired: 0,
    physicalResistance: 3,
    weight: 5,
    statModifiers: { agility: 4 },
    description: "Fly move",
  },
  {
    key: "battlebt",
    name: "Battle",
    type: "armor",
    physicalResistance: 4,
    weight: 7,
    slot: "feet",
    handsRequired: 0,
    statModifiers: { agility: 4 },
  },
  {
    key: "zombiebt",
    name: "Zombie",
    type: "armor",
    slot: "feet",
    handsRequired: 0,
    physicalResistance: 8,
    weight: 15,
    statModifiers: { agility: 8 },
    elementalResistances: { holy: 5 },
  },
  {
    key: "holybt",
    name: "Holy",
    type: "armor",
    slot: "feet",
    handsRequired: 0,
    physicalResistance: 8,
    weight: 15,
    statModifiers: { agility: 8 },
    elementalResistances: { dark: 5 },
  },
  {
    key: "tower",
    name: "Tower",
    type: "armor",
    slot: "hands",
    handsRequired: 1,
    physicalResistance: 10,
    weight: 10,
  },
  {
    key: "baldersh",
    name: "Balder",
    type: "armor",
    slot: "hands",
    handsRequired: 1,
    physicalResistance: 15,
    weight: 20,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "blacksh",
    name: "Black",
    type: "armor",
    slot: "hands",
    handsRequired: 1,
    physicalResistance: 17,
    weight: 24,
    description: "Magic resist",
  },
  {
    key: "dragonsh",
    name: "Dragon",
    type: "armor",
    slot: "hands",
    handsRequired: 1,
    physicalResistance: 20,
    weight: 30,
  },
  {
    key: "thundersh",
    name: "Thunder",
    type: "armor",
    slot: "hands",
    handsRequired: 1,
    physicalResistance: 25,
    weight: 40,
    elementalResistances: { earth: 20 },
  },
  {
    key: "flamesh",
    name: "Flame",
    type: "armor",
    slot: "hands",
    handsRequired: 1,
    physicalResistance: 25,
    weight: 40,
    elementalResistances: { water: 20 },
  },
  {
    key: "earthsh",
    name: "Earth",
    type: "armor",
    slot: "hands",
    handsRequired: 1,
    physicalResistance: 25,
    weight: 40,
    elementalResistances: { wind: 20 },
  },
  {
    key: "icesh",
    name: "Ice",
    type: "armor",
    slot: "hands",
    handsRequired: 1,
    physicalResistance: 25,
    weight: 40,
    elementalResistances: { fire: 20 },
  },
  {
    key: "angelsh",
    name: "Angel",
    type: "armor",
    slot: "hands",
    handsRequired: 1,
    physicalResistance: 25,
    weight: 40,
    elementalResistances: { dark: 20 },
  },
  {
    key: "ogresh",
    name: "Ogre",
    type: "armor",
    slot: "hands",
    handsRequired: 1,
    physicalResistance: 25,
    weight: 40,
    elementalResistances: { holy: 20 },
  },
  {
    key: "warriorgt",
    name: "Warrior",
    type: "armor",
    slot: "hands",
    handsRequired: 1,
    physicalResistance: 1,
    weight: 26,
    description: "LUK+1 at lv. up",
  },
  {
    key: "powergt",
    name: "Power",
    type: "armor",
    slot: "hands",
    handsRequired: 1,
    physicalResistance: 10,
    weight: 10,
    statModifiers: { strength: 5 },
  },
  {
    key: "baldergt",
    name: "Balder",
    type: "armor",
    slot: "hands",
    handsRequired: 1,
    physicalResistance: 13,
    weight: 16,
  },
  {
    key: "magicrg",
    name: "Magic",
    type: "armor",
    slot: "hands",
    handsRequired: 0,
    physicalResistance: 0,
    weight: 1,
    statModifiers: { intelligence: 3 },
  },
  {
    key: "floatrg",
    name: "Float",
    type: "armor",
    slot: "hands",
    handsRequired: 0,
    physicalResistance: 0,
    weight: 1,
    statModifiers: { intelligence: 3, agility: 4 },
    description: "Water walk",
  },
  {
    key: "warprg",
    name: "Warp",
    type: "armor",
    slot: "hands",
    handsRequired: 0,
    physicalResistance: 0,
    weight: 1,
    statModifiers: { intelligence: 3, agility: 4 },
    description: "Warp move",
  },
  {
    key: "wingrg",
    name: "Wing",
    type: "armor",
    slot: "hands",
    handsRequired: 0,
    physicalResistance: 0,
    weight: 1,
    statModifiers: { intelligence: 3, agility: 4 },
    description: "Fly move",
  },
  {
    key: "firerg",
    name: "Fire",
    type: "armor",
    slot: "hands",
    handsRequired: 0,
    physicalResistance: 0,
    weight: 1,
    statModifiers: { intelligence: 4 },
    elementalResistances: { water: 5 },
    description: "GlowBall",
  },
  {
    key: "aquarg",
    name: "Aqua",
    type: "armor",
    slot: "hands",
    handsRequired: 0,
    physicalResistance: 0,
    weight: 1,
    statModifiers: { intelligence: 4 },
    elementalResistances: { fire: 5 },
    description: "Hazard",
  },
  {
    key: "soilrg",
    name: "Soil",
    type: "armor",
    slot: "hands",
    handsRequired: 0,
    physicalResistance: 0,
    weight: 1,
    statModifiers: { intelligence: 4 },
    elementalResistances: { wind: 5 },
    description: "X-Zone",
  },
  {
    key: "windrg",
    name: "Wind",
    type: "armor",
    slot: "hands",
    handsRequired: 0,
    physicalResistance: 0,
    weight: 1,
    statModifiers: { intelligence: 4 },
    elementalResistances: { earth: 5 },
    description: "WindShot",
  },
  {
    key: "mindrg",
    name: "Mind",
    type: "armor",
    slot: "hands",
    handsRequired: 0,
    physicalResistance: 0,
    weight: 1,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "evilrg",
    name: "Evil",
    type: "armor",
    slot: "hands",
    handsRequired: 0,
    physicalResistance: 0,
    weight: 1,
    statModifiers: { intelligence: 8 },
    elementalResistances: { holy: 5 },
    description: "Abyss",
  },
  {
    key: "holyrg",
    name: "Holy",
    type: "armor",
    slot: "hands",
    handsRequired: 0,
    physicalResistance: 0,
    weight: 1,
    statModifiers: { intelligence: 8 },
    elementalResistances: { dark: 5 },
    description: "Banish",
  },
  {
    key: "undeadrg",
    name: "Undead",
    type: "armor",
    slot: "hands",
    handsRequired: 0,
    physicalResistance: 0,
    weight: 1,
    statModifiers: { intelligence: 8 },
  },
  {
    key: "cure",
    type: "consumable",
    name: "Cure",
    weight: 1,
    slot: "bag",
    handsRequired: 0,
  },
  {
    key: "cure2",
    type: "consumable",
    name: "Cure+",
    weight: 1,
    slot: "bag",
    handsRequired: 0,
  },
  {
    key: "cure3",
    type: "consumable",
    name: "Cure++",
    weight: 1,
    slot: "bag",
    handsRequired: 0,
  },
  {
    key: "cure4",
    type: "consumable",
    name: "Cure+++",
    weight: 1,
    slot: "bag",
    handsRequired: 0,
  },
  {
    type: "consumable",
    name: "Antidote",
    weight: 1,
    key: "antidote",
    slot: "bag",
    handsRequired: 0,
  },
  {
    key: "fireseal",
    type: "armor",
    name: "FireSeal",
    weight: 1,
    slot: "bag",
    handsRequired: 0,
    physicalResistance: 30,
    elementalResistances: {
      wind: 30,
      earth: 30,
      fire: 30,
      water: 30,
      holy: 30,
      dark: 30,
    },
  },
] as const

export const ITEM_BY_KEY = Object.fromEntries(
  ITEM_CATALOG.map((item) => [item.key, item])
)
