import { type EquippableItem } from "@/utils/combat"

export const ITEM_CATALOG: EquippableItem[] = [
  // Weapons
  {
    key: "warriorsd",
    type: "weapon",
    name: "Warrior",
    slot: "hands",
    category: "sword",
    strength: 1,
    weight: 52,
    handsRequired: 1,
    description: "LUK+1 at lvl. up",
  },
  {
    key: "mini",
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Mini",
    strength: 12,
    weight: 3,
    handsRequired: 1,
  },
  {
    key: "short",
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Short",
    strength: 15,
    weight: 7,
    handsRequired: 1,
  },
  {
    key: "balderkn",
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Balder",
    strength: 25,
    weight: 24,
    handsRequired: 1,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "desert",
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Desert",
    strength: 28,
    weight: 18,
    handsRequired: 1,
    statModifiers: { dexterity: 5 },
    description: "Petrify resist ",
  },
  {
    key: "baldersd",
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Balder",
    strength: 30,
    weight: 31,
    handsRequired: 1,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "isleberg",
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Isleberg",
    strength: 30,
    weight: 22,
    handsRequired: 2,
    statModifiers: { dexterity: 5 },
    description: "Stun resist",
  },
  {
    key: "icesd",
    type: "weapon",
    name: "Ice",
    slot: "hands",
    category: "sword",
    strength: 31,
    weight: 35,
    element: "water",
    handsRequired: 1,
    elementalResistances: { fire: 5 },
  },
  {
    key: "firesd",
    type: "weapon",
    slot: "hands",
    category: "sword",
    name: "Fire",
    strength: 32,
    weight: 32,
    element: "fire",
    handsRequired: 1,
    elementalResistances: { water: 5 },
    antiDragon: true,
  },
  {
    key: "angelsd",
    type: "weapon",
    name: "Angel",
    slot: "hands",
    category: "sword",
    strength: 32,
    weight: 23,
    element: "holy",
    handsRequired: 1,
    elementalResistances: { dark: 5 },
  },
  {
    key: "granitesd",
    type: "weapon",
    name: "Granite",
    slot: "hands",
    category: "sword",
    strength: 33,
    weight: 37,
    element: "earth",
    handsRequired: 1,
    elementalResistances: { wind: 5 },
  },
  {
    key: "fafniel",
    type: "weapon",
    name: "Fafniel",
    slot: "hands",
    category: "sword",
    strength: 33,
    weight: 37,
    handsRequired: 1,
    antiDragon: true,
  },
  {
    key: "penetent",
    type: "weapon",
    name: "Penetent",
    slot: "hands",
    category: "sword",
    strength: 34,
    weight: 28,
    handsRequired: 1,
    element: "holy",
    elementalResistances: { dark: 5 },
  },
  {
    key: "dragonsd",
    type: "weapon",
    name: "Dragon",
    slot: "hands",
    category: "sword",
    strength: 35,
    weight: 37,
    handsRequired: 2,
    antiDragon: true,
  },
  {
    key: "nyfret",
    type: "weapon",
    name: "Nyfret",
    slot: "hands",
    category: "sword",
    strength: 35,
    weight: 20,
    handsRequired: 1,
    element: "water",
    elementalResistances: { fire: 5 },
  },
  {
    key: "zenobia",
    type: "weapon",
    name: "Zenobia",
    slot: "hands",
    category: "sword",
    strength: 35,
    weight: 20,
    handsRequired: 1,
    statModifiers: { mentality: 4 },
    description: "Ailment resist",
  },
  {
    key: "ogresd",
    type: "weapon",
    name: "Ogre",
    slot: "hands",
    category: "sword",
    strength: 36,
    weight: 42,
    handsRequired: 1,
    element: "dark",
    elementalResistances: { holy: 10, dark: -5 },
    description: "Body Grab",
  },
  {
    key: "notos",
    type: "weapon",
    name: "Notos",
    slot: "hands",
    category: "sword",
    strength: 40,
    weight: 40,
    handsRequired: 2,
    element: "wind",
    elementalResistances: { earth: 5 },
  },
  {
    key: "balmuck",
    type: "weapon",
    name: "Balmuck",
    slot: "hands",
    category: "sword",
    strength: 42,
    weight: 43,
    handsRequired: 2,
  },
  {
    key: "oricon",
    type: "weapon",
    name: "Oricon",
    slot: "hands",
    category: "sword",
    strength: 45,
    weight: 39,
    handsRequired: 1,
    element: "holy",
    elementalResistances: { dark: 10, holy: -5 },
    description: "Jihad",
  },
  {
    key: "brunhild",
    type: "weapon",
    name: "Brunhild",
    slot: "hands",
    category: "sword",
    strength: 50,
    weight: 36,
    handsRequired: 1,
    element: "holy",
    elementalResistances: { dark: 15, holy: -10 },
  },
  /* {
    key: "firesn",
    type: "weapon",
    name: "Fire",
    slot: "hands",
    category: "sword",
    strength: 0,
    weight: 0,
    handsRequired: 1,
    element: "fire",
  },
  {
    key: "earthsn",
    type: "weapon",
    name: "Earth",
    slot: "hands",
    category: "sword",
    strength: 0,
    weight: 0,
    handsRequired: 1,
    element: "earth",
  },
  {
    key: "watersn",
    type: "weapon",
    name: "Water",
    slot: "hands",
    category: "sword",
    strength: 0,
    weight: 0,
    handsRequired: 1,
    element: "water",
  },
  {
    key: "windsn",
    type: "weapon",
    name: "Wind",
    slot: "hands",
    category: "sword",
    strength: 0,
    weight: 0,
    handsRequired: 1,
    element: "wind",
  },
  {
    key: "holysn",
    type: "weapon",
    name: "Holy",
    slot: "hands",
    category: "sword",
    strength: 0,
    weight: 0,
    handsRequired: 1,
    element: "holy",
  },
  {
    key: "shadowsn",
    type: "weapon",
    name: "Shadow",
    slot: "hands",
    category: "sword",
    strength: 0,
    weight: 0,
    handsRequired: 1,
    element: "dark",
  }, */
  {
    key: "phlanka",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Phlanka Axe",
    strength: 16,
    weight: 8,
    handsRequired: 1,
  },
  {
    key: "gramrock",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Gramrock",
    strength: 32,
    weight: 30,
    handsRequired: 2,
    element: "fire",
    elementalResistances: { water: 5 },
  },
  {
    key: "iceax",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Ice",
    strength: 33,
    weight: 31,
    handsRequired: 2,
    element: "water",
    elementalResistances: { fire: 5 },
  },
  {
    key: "earthax",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Gramrock",
    strength: 34,
    weight: 30,
    handsRequired: 2,
    element: "earth",
    elementalResistances: { wind: 5 },
    antiDragon: true,
  },
  {
    key: "balderax",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Balder",
    strength: 34,
    weight: 34,
    handsRequired: 2,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "procs",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Procs",
    strength: 36,
    weight: 37,
    handsRequired: 2,
    element: "fire",
    elementalResistances: { water: 5 },
  },
  {
    key: "boleas",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Boleas",
    strength: 40,
    weight: 42,
    handsRequired: 2,
    element: "wind",
    elementalResistances: { earth: 5 },
  },
  {
    key: "runeax",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Rune",
    strength: 42,
    weight: 43,
    handsRequired: 2,
    element: "holy",
    elementalResistances: { dark: 5 },
  },
  {
    key: "heavyax",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Heavy",
    strength: 45,
    weight: 49,
    handsRequired: 2,
  },
  {
    key: "bloodax",
    type: "weapon",
    slot: "hands",
    category: "axe",
    name: "Blood",
    strength: 48,
    weight: 51,
    handsRequired: 2,
    element: "dark",
    elementalResistances: { holy: 10 },
    description: "Life Suck",
  },
  {
    key: "spear",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Spear",
    strength: 12,
    weight: 9,
    handsRequired: 2,
  },
  {
    key: "slender",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Slender",
    strength: 22,
    weight: 23,
    handsRequired: 2,
  },
  {
    key: "herosp",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Hero",
    strength: 31,
    weight: 37,
    handsRequired: 2,
    element: "water",
    elementalResistances: { fire: 5 },
  },
  {
    key: "volcano",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Volcano",
    strength: 32,
    weight: 38,
    handsRequired: 2,
    element: "fire",
    elementalResistances: { water: 5 },
  },
  {
    key: "baldersp",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Balder",
    strength: 32,
    weight: 38,
    handsRequired: 2,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "earthsp",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Earth",
    strength: 34,
    weight: 36,
    handsRequired: 2,
    element: "earth",
    elementalResistances: { wind: 5 },
  },
  {
    key: "zepyulos",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Zepyulos",
    strength: 35,
    weight: 40,
    handsRequired: 2,
    element: "wind",
    elementalResistances: { earth: 5 },
  },
  {
    key: "unicorn",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Unicorn",
    strength: 42,
    weight: 52,
    handsRequired: 2,
    statModifiers: { intelligence: 9, luck: 4 },
  },
  {
    key: "evilsp",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Evil",
    strength: 43,
    weight: 51,
    handsRequired: 2,
    element: "dark",
    elementalResistances: { holy: 5 },
  },
  {
    key: "igunis",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Igunis",
    strength: 45,
    weight: 35,
    handsRequired: 2,
    element: "fire",
    elementalResistances: { water: 5 },
  },
  {
    key: "holysp",
    type: "weapon",
    slot: "hands",
    category: "spear",
    name: "Holy",
    strength: 45,
    weight: 54,
    handsRequired: 2,
    element: "holy",
    elementalResistances: { dark: 5 },
  },
  {
    type: "weapon",
    slot: "hands",
    category: "hammer",
    name: "Heavy",
    strength: 18,
    weight: 14,
    key: "heavyhm",
    handsRequired: 1,
  },
  {
    type: "weapon",
    slot: "hands",
    category: "hammer",
    name: "Aqua",
    strength: 29,
    weight: 32,
    key: "aquahm",
    element: "water",
    handsRequired: 1,
    elementalResistances: { fire: 5 },
  },
  {
    type: "weapon",
    slot: "hands",
    category: "claw",
    name: "Matou",
    strength: 24,
    weight: 21,
    key: "matou",
    handsRequired: 1,
  },
  {
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Cedar",
    strength: 6,
    weight: 2,
    key: "cedar",
    handsRequired: 1,
    statModifiers: { intelligence: 10 },
  },
  {
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Clear",
    strength: 7,
    weight: 4,
    key: "clearst",
    handsRequired: 1,
    statModifiers: { intelligence: 14, mentality: 4 },
  },
  {
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Life",
    strength: 7,
    weight: 4,
    key: "lifest",
    handsRequired: 1,
    statModifiers: { intelligence: 14, mentality: 4 },
  },
  {
    type: "weapon",
    slot: "hands",
    category: "staff",
    name: "Balder",
    strength: 7,
    weight: 7,
    key: "balderst",
    handsRequired: 1,
    statModifiers: { intelligence: 18 },
  },
  {
    type: "weapon",
    slot: "hands",
    category: "whip",
    name: "Guard",
    strength: 24,
    weight: 25,
    key: "guardwh",
    handsRequired: 2,
  },
  {
    key: "rimfire",
    type: "weapon",
    slot: "hands",
    name: "RimFire",
    category: "gun",
    strength: 7,
    weight: 22,
    handsRequired: 1,
  },
  {
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Short",
    strength: 10,
    weight: 6,
    key: "shortbw",
    handsRequired: 1,
  },
  {
    key: "greatbw",
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Great",
    strength: 15,
    weight: 15,
    handsRequired: 2,
  },
  {
    type: "weapon",
    slot: "hands",
    category: "bow",
    name: "Balder",
    strength: 21,
    weight: 32,
    key: "balderbw",
    handsRequired: 2,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "crossbow",
    name: "Crossbow",
    type: "weapon",
    slot: "hands",
    category: "crossbow",
    strength: 15,
    weight: 24,
    handsRequired: 1,
  },
  {
    key: "gemini",
    type: "weapon",
    name: "Gemini",
    slot: "hands",
    category: "crossbow",
    strength: 23,
    weight: 36,
    handsRequired: 2,
  },
  // Armor
  {
    type: "armor",
    name: "Leather",
    physicalResistance: 3,
    weight: 6,
    key: "leatherar",
    slot: "body",
    handsRequired: 0,
  },
  {
    type: "armor",
    name: "Chain",
    physicalResistance: 6,
    weight: 12,
    key: "chainar",
    slot: "body",
    handsRequired: 0,
  },
  {
    key: "balderar",
    type: "armor",
    name: "Balder",
    physicalResistance: 9,
    weight: 18,
    slot: "body",
    handsRequired: 0,
    statModifiers: { intelligence: 5 },
  },
  {
    type: "armor",
    name: "Robe",
    physicalResistance: 1,
    weight: 1,
    key: "robe",
    slot: "body",
    handsRequired: 0,
  },
  {
    type: "armor",
    name: "Balder",
    physicalResistance: 4,
    weight: 3,
    key: "balderrb",
    slot: "body",
    handsRequired: 0,
    statModifiers: { intelligence: 5 },
  },
  {
    type: "armor",
    name: "Leather",
    physicalResistance: 2,
    weight: 4,
    key: "leatherht",
    slot: "head",
    handsRequired: 0,
  },
  {
    type: "armor",
    name: "Balder",
    physicalResistance: 6,
    weight: 12,
    key: "balderht",
    slot: "head",
    handsRequired: 0,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "bluenk",
    name: "Blue",
    type: "armor",
    physicalResistance: 0,
    weight: 1,
    slot: "head",
    handsRequired: 0,
    statModifiers: { mentality: 10 },
    elementalResistances: { dark: 5 },
    description: "Ailment resist",
  },
  {
    key: "rednk",
    name: "Red",
    type: "armor",
    physicalResistance: 0,
    weight: 1,
    slot: "head",
    handsRequired: 0,
    statModifiers: { mentality: 10 },
    elementalResistances: { dark: 5 },
    description: "Ailment resist",
  },
  {
    type: "armor",
    name: "Battle",
    physicalResistance: 4,
    weight: 7,
    key: "battlebt",
    slot: "feet",
    handsRequired: 0,
    statModifiers: { agility: 4 },
  },
  {
    type: "armor",
    name: "Tower",
    physicalResistance: 10,
    weight: 10,
    key: "tower",
    slot: "hands",
    handsRequired: 1,
  },
  {
    type: "armor",
    name: "Balder",
    physicalResistance: 15,
    weight: 20,
    key: "baldersh",
    slot: "hands",
    handsRequired: 1,
    statModifiers: { intelligence: 5 },
  },
  {
    type: "armor",
    name: "Power",
    physicalResistance: 10,
    weight: 10,
    key: "powergt",
    slot: "hands",
    handsRequired: 1,
    statModifiers: { strength: 5 },
  },
  {
    type: "armor",
    name: "Balder",
    physicalResistance: 13,
    weight: 16,
    key: "baldergt",
    slot: "hands",
    handsRequired: 1,
  },
  {
    type: "armor",
    name: "Magic",
    physicalResistance: 0,
    weight: 1,
    key: "magicrg",
    slot: "hands",
    handsRequired: 0,
    statModifiers: { intelligence: 3 },
  },
  {
    type: "armor",
    name: "Mind",
    physicalResistance: 0,
    weight: 1,
    key: "mindrg",
    slot: "hands",
    handsRequired: 0,
    statModifiers: { intelligence: 5 },
  },
  {
    key: "cure",
    type: "consumable",
    name: "Cure",
    weight: 1,
    slot: "bag",
    handsRequired: 0,
  },
  {
    key: "cure2",
    type: "consumable",
    name: "Cure+",
    weight: 1,
    slot: "bag",
    handsRequired: 0,
  },
  {
    key: "cure3",
    type: "consumable",
    name: "Cure++",
    weight: 1,
    slot: "bag",
    handsRequired: 0,
  },
  {
    key: "cure4",
    type: "consumable",
    name: "Cure+++",
    weight: 1,
    slot: "bag",
    handsRequired: 0,
  },
  {
    type: "consumable",
    name: "Antidote",
    weight: 1,
    key: "antidote",
    slot: "bag",
    handsRequired: 0,
  },
  {
    key: "fireseal",
    type: "armor",
    name: "FireSeal",
    weight: 1,
    slot: "bag",
    handsRequired: 0,
    physicalResistance: 30,
    elementalResistances: {
      wind: 30,
      earth: 30,
      fire: 30,
      water: 30,
      holy: 30,
      dark: 30,
    },
  },
] as const

export const ITEM_BY_KEY = Object.fromEntries(
  ITEM_CATALOG.map((item) => [item.key, item])
)
