import {
  type WeaponStats,
  type ArmorStats,
  type ConsumableStats,
} from "@/utils/combat"

export const ITEM_CATALOG: (WeaponStats | ArmorStats | ConsumableStats)[] = [
  // Weapons
  {
    name: "Mini Dagger",
    strength: 12,
    weight: 3,
    type: "weapon",
    iconName: "mini",
  },
  {
    name: "Short Sword",
    strength: 15,
    weight: 7,
    type: "weapon",
    iconName: "short",
  },
  {
    name: "Balder Dagger",
    strength: 25,
    weight: 24,
    type: "weapon",
    iconName: "balderkn",
  },
  {
    name: "Balder Sword",
    strength: 30,
    weight: 31,
    type: "weapon",
    iconName: "baldersd",
  },
  {
    name: "Fire Sword",
    strength: 32,
    weight: 32,
    type: "weapon",
    iconName: "firesd",
    element: "fire",
  },
  {
    name: "Phlanka Axe",
    strength: 16,
    weight: 8,
    type: "weapon",
    iconName: "phlanka",
  },
  {
    name: "Spear",
    strength: 12,
    weight: 9,
    type: "weapon",
    iconName: "spear",
  },
  {
    name: "Slender Spear",
    strength: 22,
    weight: 23,
    type: "weapon",
    iconName: "slender",
  },
  {
    name: "Heavy Hammer",
    strength: 18,
    weight: 14,
    type: "weapon",
    iconName: "heavyhm",
  },
  {
    name: "Aqua Hammer",
    strength: 29,
    weight: 32,
    type: "weapon",
    iconName: "aquahm",
    element: "water",
  },
  {
    name: "Matou",
    strength: 24,
    weight: 21,
    type: "weapon",
    iconName: "matou",
  },
  {
    name: "Cedar Staff",
    strength: 6,
    weight: 2,
    type: "weapon",
    iconName: "cedar",
  },
  {
    name: "Clear Staff",
    strength: 7,
    weight: 4,
    type: "weapon",
    iconName: "clearst",
  },
  {
    name: "Life Staff",
    strength: 7,
    weight: 4,
    type: "weapon",
    iconName: "lifest",
  },
  {
    name: "Balder Staff",
    strength: 7,
    weight: 7,
    type: "weapon",
    iconName: "balderst",
  },
  {
    name: "Guard Whip",
    strength: 24,
    weight: 25,
    type: "weapon",
    iconName: "guardwh",
  },
  {
    name: "Short Bow",
    strength: 10,
    weight: 6,
    type: "weapon",
    iconName: "shortbw",
  },
  {
    name: "Great Bow",
    strength: 15,
    weight: 15,
    type: "weapon",
    iconName: "greatbw",
  },
  {
    name: "Balder Bow",
    strength: 21,
    weight: 32,
    type: "weapon",
    iconName: "balderbw",
  },
  {
    name: "Crossbow",
    strength: 15,
    weight: 24,
    type: "weapon",
    iconName: "crossbow",
  },
  {
    name: "Gemini Crossbow",
    strength: 23,
    weight: 36,
    type: "weapon",
    iconName: "gemini",
  },
  // Armor
  {
    name: "Leather Armor",
    physicalResistance: 3,
    weight: 6,
    type: "armor",
    iconName: "leatherar",
  },
  {
    name: "Chain Mail",
    physicalResistance: 6,
    weight: 12,
    type: "armor",
    iconName: "chainar",
  },
  {
    name: "Balder Armor",
    physicalResistance: 9,
    weight: 18,
    type: "armor",
    iconName: "balderar",
  },
  {
    name: "Robe",
    physicalResistance: 1,
    weight: 1,
    type: "armor",
    iconName: "robe",
  },
  {
    name: "Balder Robe",
    physicalResistance: 4,
    weight: 3,
    type: "armor",
    iconName: "balderrb",
  },
  {
    name: "Leather Cap",
    physicalResistance: 2,
    weight: 4,
    type: "armor",
    iconName: "leatherht",
  },
  {
    name: "Balder Helmet",
    physicalResistance: 6,
    weight: 12,
    type: "armor",
    iconName: "balderht",
  },
  {
    name: "Battle Boots",
    physicalResistance: 4,
    weight: 7,
    type: "armor",
    iconName: "battlebt",
  },
  {
    name: "Tower Shield",
    physicalResistance: 10,
    weight: 10,
    type: "armor",
    iconName: "tower",
  },
  {
    name: "Balder Shield",
    physicalResistance: 15,
    weight: 20,
    type: "armor",
    iconName: "baldersh",
  },
  {
    name: "Power Gauntlet",
    physicalResistance: 10,
    weight: 10,
    type: "armor",
    iconName: "powergt",
  },
  {
    name: "Balder Gauntlet",
    physicalResistance: 13,
    weight: 16,
    type: "armor",
    iconName: "baldergt",
  },
  {
    name: "Magic Ring",
    physicalResistance: 0,
    weight: 1,
    type: "armor",
    iconName: "magicrg",
  },
  {
    name: "Mind Ring",
    physicalResistance: 0,
    weight: 1,
    type: "armor",
    iconName: "mindrg",
  },
  {
    name: "Cure",
    weight: 1,
    type: "consumable",
    iconName: "cure",
  },
  {
    name: "Cure+",
    weight: 1,
    type: "consumable",
    iconName: "cure2",
  },
  {
    name: "Antidote",
    weight: 1,
    type: "consumable",
    iconName: "antidote",
  },
]
